const BALATRO_WIKI_BASE = 'https://balatrowiki.org'

export const BALATRO_JOKERS = [
  { name: 'Joker', image: `${BALATRO_WIKI_BASE}/images/Joker.png` },
  { name: 'Greedy Joker', image: `${BALATRO_WIKI_BASE}/images/Greedy_Joker.png` },
  { name: 'Lusty Joker', image: `${BALATRO_WIKI_BASE}/images/Lusty_Joker.png` },
  { name: 'Wrathful Joker', image: `${BALATRO_WIKI_BASE}/images/Wrathful_Joker.png` },
  { name: 'Gluttonous Joker', image: `${BALATRO_WIKI_BASE}/images/Gluttonous_Joker.png` },
  { name: 'Jolly Joker', image: `${BALATRO_WIKI_BASE}/images/Jolly_Joker.png` },
  { name: 'Zany Joker', image: `${BALATRO_WIKI_BASE}/images/Zany_Joker.png` },
  { name: 'Mad Joker', image: `${BALATRO_WIKI_BASE}/images/Mad_Joker.png` },
  { name: 'Crazy Joker', image: `${BALATRO_WIKI_BASE}/images/Crazy_Joker.png` },
  { name: 'Droll Joker', image: `${BALATRO_WIKI_BASE}/images/Droll_Joker.png` },
  { name: 'Sly Joker', image: `${BALATRO_WIKI_BASE}/images/Sly_Joker.png` },
  { name: 'Wily Joker', image: `${BALATRO_WIKI_BASE}/images/Wily_Joker.png` },
  { name: 'Clever Joker', image: `${BALATRO_WIKI_BASE}/images/Clever_Joker.png` },
  { name: 'Devious Joker', image: `${BALATRO_WIKI_BASE}/images/Devious_Joker.png` },
  { name: 'Crafty Joker', image: `${BALATRO_WIKI_BASE}/images/Crafty_Joker.png` },
  { name: 'Half Joker', image: `${BALATRO_WIKI_BASE}/images/Half_Joker.png` },
  { name: 'Joker Stencil', image: `${BALATRO_WIKI_BASE}/images/Joker_Stencil.png` },
  { name: 'Four Fingers', image: `${BALATRO_WIKI_BASE}/images/Four_Fingers.png` },
  { name: 'Mime', image: `${BALATRO_WIKI_BASE}/images/Mime.png` },
  { name: 'Credit Card', image: `${BALATRO_WIKI_BASE}/images/Credit_Card.png` },
  { name: 'Ceremonial Dagger', image: `${BALATRO_WIKI_BASE}/images/Ceremonial_Dagger.png` },
  { name: 'Banner', image: `${BALATRO_WIKI_BASE}/images/Banner.png` },
  { name: 'Mystic Summit', image: `${BALATRO_WIKI_BASE}/images/Mystic_Summit.png` },
  { name: 'Marble Joker', image: `${BALATRO_WIKI_BASE}/images/Marble_Joker.png` },
  { name: 'Loyalty Card', image: `${BALATRO_WIKI_BASE}/images/Loyalty_Card.png` },
  { name: '8 Ball', image: `${BALATRO_WIKI_BASE}/images/8_Ball.png` },
  { name: 'Misprint', image: `${BALATRO_WIKI_BASE}/images/Misprint.png` },
  { name: 'Dusk', image: `${BALATRO_WIKI_BASE}/images/Dusk.png` },
  { name: 'Raised Fist', image: `${BALATRO_WIKI_BASE}/images/Raised_Fist.png` },
  { name: 'Chaos the Clown', image: `${BALATRO_WIKI_BASE}/images/Chaos_the_Clown.png` },
  { name: 'Fibonacci', image: `${BALATRO_WIKI_BASE}/images/Fibonacci.png` },
  { name: 'Steel Joker', image: `${BALATRO_WIKI_BASE}/images/Steel_Joker.png` },
  { name: 'Scary Face', image: `${BALATRO_WIKI_BASE}/images/Scary_Face.png` },
  { name: 'Abstract Joker', image: `${BALATRO_WIKI_BASE}/images/Abstract_Joker.png` },
  { name: 'Delayed Gratification', image: `${BALATRO_WIKI_BASE}/images/Delayed_Gratification.png` },
  { name: 'Hack', image: `${BALATRO_WIKI_BASE}/images/Hack.png` },
  { name: 'Pareidolia', image: `${BALATRO_WIKI_BASE}/images/Pareidolia.png` },
  { name: 'Gros Michel', image: `${BALATRO_WIKI_BASE}/images/Gros_Michel.png` },
  { name: 'Even Steven', image: `${BALATRO_WIKI_BASE}/images/Even_Steven.png` },
  { name: 'Odd Todd', image: `${BALATRO_WIKI_BASE}/images/Odd_Todd.png` },
  { name: 'Scholar', image: `${BALATRO_WIKI_BASE}/images/Scholar.png` },
  { name: 'Business Card', image: `${BALATRO_WIKI_BASE}/images/Business_Card.png` },
  { name: 'Supernova', image: `${BALATRO_WIKI_BASE}/images/Supernova.png` },
  { name: 'Ride the Bus', image: `${BALATRO_WIKI_BASE}/images/Ride_the_Bus.png` },
  { name: 'Space Joker', image: `${BALATRO_WIKI_BASE}/images/Space_Joker.png` },
  { name: 'Egg', image: `${BALATRO_WIKI_BASE}/images/Egg.png` },
  { name: 'Burglar', image: `${BALATRO_WIKI_BASE}/images/Burglar.png` },
  { name: 'Blackboard', image: `${BALATRO_WIKI_BASE}/images/Blackboard.png` },
  { name: 'Runner', image: `${BALATRO_WIKI_BASE}/images/Runner.png` },
  { name: 'Ice Cream', image: `${BALATRO_WIKI_BASE}/images/Ice_Cream.png` },
  { name: 'DNA', image: `${BALATRO_WIKI_BASE}/images/DNA.png` },
  { name: 'Splash', image: `${BALATRO_WIKI_BASE}/images/Splash.png` },
  { name: 'Blue Joker', image: `${BALATRO_WIKI_BASE}/images/Blue_Joker.png` },
  { name: 'Sixth Sense', image: `${BALATRO_WIKI_BASE}/images/Sixth_Sense.png` },
  { name: 'Constellation', image: `${BALATRO_WIKI_BASE}/images/Constellation.png` },
  { name: 'Hiker', image: `${BALATRO_WIKI_BASE}/images/Hiker.png` },
  { name: 'Faceless Joker', image: `${BALATRO_WIKI_BASE}/images/Faceless_Joker.png` },
  { name: 'Green Joker', image: `${BALATRO_WIKI_BASE}/images/Green_Joker.png` },
  { name: 'Superposition', image: `${BALATRO_WIKI_BASE}/images/Superposition.png` },
  { name: 'To Do List', image: `${BALATRO_WIKI_BASE}/images/To_Do_List.png` },
  { name: 'Cavendish', image: `${BALATRO_WIKI_BASE}/images/Cavendish.png` },
  { name: 'Card Sharp', image: `${BALATRO_WIKI_BASE}/images/Card_Sharp.png` },
  { name: 'Red Card', image: `${BALATRO_WIKI_BASE}/images/Red_Card.png` },
  { name: 'Madness', image: `${BALATRO_WIKI_BASE}/images/Madness.png` },
  { name: 'Square Joker', image: `${BALATRO_WIKI_BASE}/images/Square_Joker.png` },
  { name: 'Séance', image: `${BALATRO_WIKI_BASE}/images/S%C3%A9ance.png` },
  { name: 'Riff-Raff', image: `${BALATRO_WIKI_BASE}/images/Riff-Raff.png` },
  { name: 'Vampire', image: `${BALATRO_WIKI_BASE}/images/Vampire.png` },
  { name: 'Shortcut', image: `${BALATRO_WIKI_BASE}/images/Shortcut.png` },
  { name: 'Hologram', image: `${BALATRO_WIKI_BASE}/images/Hologram.gif` },
  { name: 'Vagabond', image: `${BALATRO_WIKI_BASE}/images/Vagabond.png` },
  { name: 'Baron', image: `${BALATRO_WIKI_BASE}/images/Baron.png` },
  { name: 'Cloud 9', image: `${BALATRO_WIKI_BASE}/images/Cloud_9.png` },
  { name: 'Rocket', image: `${BALATRO_WIKI_BASE}/images/Rocket.png` },
  { name: 'Obelisk', image: `${BALATRO_WIKI_BASE}/images/Obelisk.png` },
  { name: 'Midas Mask', image: `${BALATRO_WIKI_BASE}/images/Midas_Mask.png` },
  { name: 'Luchador', image: `${BALATRO_WIKI_BASE}/images/Luchador.png` },
  { name: 'Photograph', image: `${BALATRO_WIKI_BASE}/images/Photograph.png` },
  { name: 'Gift Card', image: `${BALATRO_WIKI_BASE}/images/Gift_Card.png` },
  { name: 'Turtle Bean', image: `${BALATRO_WIKI_BASE}/images/Turtle_Bean.png` },
  { name: 'Erosion', image: `${BALATRO_WIKI_BASE}/images/Erosion.png` },
  { name: 'Reserved Parking', image: `${BALATRO_WIKI_BASE}/images/Reserved_Parking.png` },
  { name: 'Mail-In Rebate', image: `${BALATRO_WIKI_BASE}/images/Mail-In_Rebate.png` },
  { name: 'To the Moon', image: `${BALATRO_WIKI_BASE}/images/To_the_Moon.png` },
  { name: 'Hallucination', image: `${BALATRO_WIKI_BASE}/images/Hallucination.png` },
  { name: 'Fortune Teller', image: `${BALATRO_WIKI_BASE}/images/Fortune_Teller.png` },
  { name: 'Juggler', image: `${BALATRO_WIKI_BASE}/images/Juggler.png` },
  { name: 'Drunkard', image: `${BALATRO_WIKI_BASE}/images/Drunkard.png` },
  { name: 'Stone Joker', image: `${BALATRO_WIKI_BASE}/images/Stone_Joker.png` },
  { name: 'Golden Joker', image: `${BALATRO_WIKI_BASE}/images/Golden_Joker.png` },
  { name: 'Lucky Cat', image: `${BALATRO_WIKI_BASE}/images/Lucky_Cat.png` },
  { name: 'Baseball Card', image: `${BALATRO_WIKI_BASE}/images/Baseball_Card.png` },
  { name: 'Bull', image: `${BALATRO_WIKI_BASE}/images/Bull.png` },
  { name: 'Diet Cola', image: `${BALATRO_WIKI_BASE}/images/Diet_Cola.png` },
  { name: 'Trading Card', image: `${BALATRO_WIKI_BASE}/images/Trading_Card.png` },
  { name: 'Flash Card', image: `${BALATRO_WIKI_BASE}/images/Flash_Card.png` },
  { name: 'Popcorn', image: `${BALATRO_WIKI_BASE}/images/Popcorn.png` },
  { name: 'Spare Trousers', image: `${BALATRO_WIKI_BASE}/images/Spare_Trousers.png` },
  { name: 'Ancient Joker', image: `${BALATRO_WIKI_BASE}/images/Ancient_Joker.png` },
  { name: 'Ramen', image: `${BALATRO_WIKI_BASE}/images/Ramen.png` },
  { name: 'Walkie Talkie', image: `${BALATRO_WIKI_BASE}/images/Walkie_Talkie.png` },
  { name: 'Seltzer', image: `${BALATRO_WIKI_BASE}/images/Seltzer.png` },
  { name: 'Castle', image: `${BALATRO_WIKI_BASE}/images/Castle.png` },
  { name: 'Smiley Face', image: `${BALATRO_WIKI_BASE}/images/Smiley_Face.png` },
  { name: 'Campfire', image: `${BALATRO_WIKI_BASE}/images/Campfire.png` },
  { name: 'Golden Ticket', image: `${BALATRO_WIKI_BASE}/images/Golden_Ticket.png` },
  { name: 'Mr. Bones', image: `${BALATRO_WIKI_BASE}/images/Mr._Bones.png` },
  { name: 'Acrobat', image: `${BALATRO_WIKI_BASE}/images/Acrobat.png` },
  { name: 'Sock and Buskin', image: `${BALATRO_WIKI_BASE}/images/Sock_and_Buskin.png` },
  { name: 'Swashbuckler', image: `${BALATRO_WIKI_BASE}/images/Swashbuckler.png` },
  { name: 'Troubadour', image: `${BALATRO_WIKI_BASE}/images/Troubadour.png` },
  { name: 'Certificate', image: `${BALATRO_WIKI_BASE}/images/Certificate.png` },
  { name: 'Smeared Joker', image: `${BALATRO_WIKI_BASE}/images/Smeared_Joker.png` },
  { name: 'Throwback', image: `${BALATRO_WIKI_BASE}/images/Throwback.png` },
  { name: 'Hanging Chad', image: `${BALATRO_WIKI_BASE}/images/Hanging_Chad.png` },
  { name: 'Rough Gem', image: `${BALATRO_WIKI_BASE}/images/Rough_Gem.png` },
  { name: 'Bloodstone', image: `${BALATRO_WIKI_BASE}/images/Bloodstone.png` },
  { name: 'Arrowhead', image: `${BALATRO_WIKI_BASE}/images/Arrowhead.png` },
  { name: 'Onyx Agate', image: `${BALATRO_WIKI_BASE}/images/Onyx_Agate.png` },
  { name: 'Glass Joker', image: `${BALATRO_WIKI_BASE}/images/Glass_Joker.png` },
  { name: 'Showman', image: `${BALATRO_WIKI_BASE}/images/Showman.png` },
  { name: 'Flower Pot', image: `${BALATRO_WIKI_BASE}/images/Flower_Pot.png` },
  { name: 'Blueprint', image: `${BALATRO_WIKI_BASE}/images/Blueprint.png` },
  { name: 'Wee Joker', image: `${BALATRO_WIKI_BASE}/images/Wee_Joker.png` },
  { name: 'Merry Andy', image: `${BALATRO_WIKI_BASE}/images/Merry_Andy.png` },
  { name: 'Oops! All 6s', image: `${BALATRO_WIKI_BASE}/images/Oops%21_All_6s.png` },
  { name: 'The Idol', image: `${BALATRO_WIKI_BASE}/images/The_Idol.png` },
  { name: 'Seeing Double', image: `${BALATRO_WIKI_BASE}/images/Seeing_Double.png` },
  { name: 'Matador', image: `${BALATRO_WIKI_BASE}/images/Matador.png` },
  { name: 'Hit the Road', image: `${BALATRO_WIKI_BASE}/images/Hit_the_Road.png` },
  { name: 'The Duo', image: `${BALATRO_WIKI_BASE}/images/The_Duo.png` },
  { name: 'The Trio', image: `${BALATRO_WIKI_BASE}/images/The_Trio.png` },
  { name: 'The Family', image: `${BALATRO_WIKI_BASE}/images/The_Family.png` },
  { name: 'The Order', image: `${BALATRO_WIKI_BASE}/images/The_Order.png` },
  { name: 'The Tribe', image: `${BALATRO_WIKI_BASE}/images/The_Tribe.png` },
  { name: 'Stuntman', image: `${BALATRO_WIKI_BASE}/images/Stuntman.png` },
  { name: 'Invisible Joker', image: `${BALATRO_WIKI_BASE}/images/Invisible_Joker.png` },
  { name: 'Brainstorm', image: `${BALATRO_WIKI_BASE}/images/Brainstorm.png` },
  { name: 'Satellite', image: `${BALATRO_WIKI_BASE}/images/Satellite.png` },
  { name: 'Shoot the Moon', image: `${BALATRO_WIKI_BASE}/images/Shoot_the_Moon.png` },
  { name: "Driver's License", image: `${BALATRO_WIKI_BASE}/images/Driver%27s_License.png` },
  { name: 'Cartomancer', image: `${BALATRO_WIKI_BASE}/images/Cartomancer.png` },
  { name: 'Astronomer', image: `${BALATRO_WIKI_BASE}/images/Astronomer.png` },
  { name: 'Burnt Joker', image: `${BALATRO_WIKI_BASE}/images/Burnt_Joker.png` },
  { name: 'Bootstraps', image: `${BALATRO_WIKI_BASE}/images/Bootstraps.png` },
  { name: 'Canio', image: `${BALATRO_WIKI_BASE}/images/Canio.png` },
  { name: 'Triboulet', image: `${BALATRO_WIKI_BASE}/images/Triboulet.png` },
  { name: 'Yorick', image: `${BALATRO_WIKI_BASE}/images/Yorick.png` },
  { name: 'Chicot', image: `${BALATRO_WIKI_BASE}/images/Chicot.png` },
  { name: 'Perkeo', image: `${BALATRO_WIKI_BASE}/images/Perkeo.png` },
] as const
